Bittrex Ticker API support
OttoAllmendinger/gnome-shell-bitcoin-markets pull request #106
Opened 2021-01-08 17:42 UTC by luissantos

I would like to add support for Bittrex exchange.
Please let me know if something else is required before I can submit my changes.

2021-01-11 07:43 UTC, OttoAllmendinger commented on src/ApiService.ts
> +import * as ProviderBittrex from './providers/ProviderBittrex';
please add it in alphabetical order

2021-01-11 07:43 UTC, OttoAllmendinger requested changes
see comment

2021-01-28 11:49 UTC, luissantos commented on src/ApiService.ts
> +import * as ProviderBittrex from './providers/ProviderBittrex';
done.

2021-03-24 11:09 UTC, OttoAllmendinger commented
thanks! merged

2021-03-24 11:09 UTC, closed without merging