Add Nobitex provider
OttoAllmendinger/gnome-shell-bitcoin-markets pull request #156
Opened 2024-08-05 11:33 UTC by itismoej

Tested locally on Ubuntu 24.04 LTS, works fine.

![image](https://github.com/user-attachments/assets/0b53da18-1189-4c2d-81b4-c72ed2ff73bd)

![image](https://github.com/user-attachments/assets/e584e128-ca7c-40ee-a682-76ca50dc43f1)

2024-09-13 13:36 UTC, itismoej commented
Ping! @OttoAllmendinger 

Can we merge this PR?

2024-12-07 12:19 UTC, OttoAllmendinger requested changes
please remove the yarn.lock

2024-12-07 12:33 UTC, itismoej commented
> please remove the yarn.lock

removed it

2024-12-07 12:39 UTC, OttoAllmendinger approved these changes

2024-12-07 12:39 UTC, merged